---
#Install LAMP
lamp_package: [ 'acl', 'unzip', 'sendmail', 'mysql-server', 'python3-pymysql', 'python3-pycurl', 'python3-mysqldb', 'php', 'libapache2-mod-php', 'libpcre3-dev'  ] 

#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip', 'php-cli', 'php-dev', 'php-imagick', 'php-json', 'php7.4-opcache', 'php7.4-pdo', 'php-mysql', 'php7.4-mysqli', 'php7.4-mysqlnd', 'php-apcu' ]



#MySQL Settings
mysql_root_password: ""
mysql_db: "wp1_mary"
mysql_wp_user: "wp1_mary"
mysql_wp_password: "wp1_12345"

#HTTP Settings
http_host: "your_domain"
http_conf: "your_domain.conf"
http_port: "80"

# The path where WordPress will be installed.
wordpress_core_path: "/var/www/wordpress"

# Your WordPress site name.
wordpress_site_name: "WordPress Test"

#Domain name without www, http, https
domain: "wordpress.test"

#WordPress Settings
wp_user: "admin"
wp_user_pass: "Admin!!345"
wp_siteurl: "wordpress.test"
wp_admin_email: "info@wordpress.test"
wp_cli_phar_url: https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
wp_cli_bin_path: "/usr/bin/{{ wp_cli_bin_command }}"
wp_cli_bin_command: wp
wordpress_installs:
  - { dbname: wp1_mary, dbuser: wp1_mary, dbpass: wp1_12345 }

